import type { InferInsertModel } from "drizzle-orm";

import {
  amendments,
  charges,
  events,
  subscriptions,
  users,
} from "./schema";

export const DEFAULT_SEED_EMAIL = "seed@example.com";
export const SEED_USER_ID = "00000000-0000-4000-8000-000000000001";

type SubscriptionInsert = InferInsertModel<typeof subscriptions>;
type AmendmentInsert = InferInsertModel<typeof amendments>;
type EventInsert = InferInsertModel<typeof events>;
type ChargeInsert = InferInsertModel<typeof charges>;
type SubscriptionKey = keyof typeof SEED_SUBSCRIPTION_IDS;
type SeedSubscription = SubscriptionInsert & { key: SubscriptionKey };

export type SeedData = {
  user: InferInsertModel<typeof users>;
  subscriptions: SubscriptionInsert[];
  amendments: AmendmentInsert[];
  events: EventInsert[];
  charges: ChargeInsert[];
};

function dateAtOffset(today: Date, days: number) {
  const result = new Date(
    Date.UTC(today.getUTCFullYear(), today.getUTCMonth(), today.getUTCDate()),
  );
  result.setUTCDate(result.getUTCDate() + days);
  return result.toISOString().slice(0, 10);
}

export function getSeedDates(today: Date) {
  return {
    today: dateAtOffset(today, 0),
    startedOn: dateAtOffset(today, -365),
    renewalSoon: dateAtOffset(today, 3),
    renewalWithin30: dateAtOffset(today, 21),
    trialEndsOn: dateAtOffset(today, 8),
    cancelEndsOn: dateAtOffset(today, 27),
    cancelledOn: dateAtOffset(today, -30),
    recentChargeOn: dateAtOffset(today, -12),
    olderChargeOn: dateAtOffset(today, -42),
    eventAt: new Date(
      Date.UTC(today.getUTCFullYear(), today.getUTCMonth(), today.getUTCDate()),
    ),
  };
}

export const SEED_SUBSCRIPTION_IDS = {
  netflix: "00000000-0000-4000-8000-000000001001",
  spotify: "00000000-0000-4000-8000-000000001002",
  icloud: "00000000-0000-4000-8000-000000001003",
  claudePro: "00000000-0000-4000-8000-000000001004",
  cursor: "00000000-0000-4000-8000-000000001005",
  github: "00000000-0000-4000-8000-000000001006",
  adobe: "00000000-0000-4000-8000-000000001007",
  notion: "00000000-0000-4000-8000-000000001008",
  onePassword: "00000000-0000-4000-8000-000000001009",
  athletic: "00000000-0000-4000-8000-000000001010",
  disneyPlus: "00000000-0000-4000-8000-000000001011",
} as const;

export const SEED_AMENDMENT_IDS = {
  netflix: "00000000-0000-4000-8000-000000002001",
  spotify: "00000000-0000-4000-8000-000000002002",
  icloud: "00000000-0000-4000-8000-000000002003",
  claudePro: "00000000-0000-4000-8000-000000002004",
  cursor: "00000000-0000-4000-8000-000000002005",
  github: "00000000-0000-4000-8000-000000002006",
  adobe: "00000000-0000-4000-8000-000000002007",
  notion: "00000000-0000-4000-8000-000000002008",
  onePassword: "00000000-0000-4000-8000-000000002009",
  athletic: "00000000-0000-4000-8000-000000002010",
  disneyPlus: "00000000-0000-4000-8000-000000002011",
} as const;

export const SEED_EVENT_IDS = {
  netflix: "00000000-0000-4000-8000-000000003001",
  spotify: "00000000-0000-4000-8000-000000003002",
  icloud: "00000000-0000-4000-8000-000000003003",
  claudePro: "00000000-0000-4000-8000-000000003004",
  cursor: "00000000-0000-4000-8000-000000003005",
  github: "00000000-0000-4000-8000-000000003006",
  adobe: "00000000-0000-4000-8000-000000003007",
  notion: "00000000-0000-4000-8000-000000003008",
  onePassword: "00000000-0000-4000-8000-000000003009",
  athletic: "00000000-0000-4000-8000-000000003010",
  disneyPlus: "00000000-0000-4000-8000-000000003011",
} as const;

const chargeIds = {
  netflix: "00000000-0000-4000-8000-000000004001",
  spotify: "00000000-0000-4000-8000-000000004002",
} as const;

export function createSeedData(
  today: Date,
  email = DEFAULT_SEED_EMAIL,
): SeedData {
  const dates = getSeedDates(today);
  const user = {
    id: SEED_USER_ID,
    name: "Seed user",
    email: email.trim().toLowerCase(),
    email_verified: null,
    image: null,
  } satisfies InferInsertModel<typeof users>;

  const subscriptionRows = {
    netflix: {
      key: "netflix",
      id: SEED_SUBSCRIPTION_IDS.netflix,
      user_id: SEED_USER_ID,
      provider_canonical: "netflix",
      provider_display: "Netflix",
      plan: "Standard",
      account_hint: null,
      status: "active",
      amount_minor: 1599,
      currency: "GBP",
      cadence: "monthly",
      next_renewal: dates.renewalSoon,
      started_on: dates.startedOn,
      ends_on: null,
      notes: null,
      provider_field_status: "confirmed",
      amount_field_status: "confirmed",
      cadence_field_status: "confirmed",
      renewal_field_status: "confirmed",
      status_field_status: "confirmed",
      amount_confidence: "high",
      cadence_confidence: "high",
      renewal_confidence: "high",
      provider_confidence: "high",
      status_confidence: "high",
      deferred_until: null,
    },
    spotify: {
      key: "spotify",
      id: SEED_SUBSCRIPTION_IDS.spotify,
      user_id: SEED_USER_ID,
      provider_canonical: "spotify",
      provider_display: "Spotify",
      plan: "Premium",
      account_hint: null,
      status: "active",
      amount_minor: 1199,
      currency: "GBP",
      cadence: "monthly",
      next_renewal: dates.renewalWithin30,
      started_on: dates.startedOn,
      ends_on: null,
      notes: null,
      provider_field_status: "confirmed",
      amount_field_status: "confirmed",
      cadence_field_status: "confirmed",
      renewal_field_status: "confirmed",
      status_field_status: "confirmed",
      amount_confidence: "high",
      cadence_confidence: "high",
      renewal_confidence: "high",
      provider_confidence: "high",
      status_confidence: "high",
      deferred_until: null,
    },
    icloud: {
      key: "icloud",
      id: SEED_SUBSCRIPTION_IDS.icloud,
      user_id: SEED_USER_ID,
      provider_canonical: "icloud",
      provider_display: "iCloud",
      plan: "200 GB",
      account_hint: null,
      status: "active",
      amount_minor: 299,
      currency: "GBP",
      cadence: "monthly",
      next_renewal: dateAtOffset(today, 14),
      started_on: dates.startedOn,
      ends_on: null,
      notes: null,
      provider_field_status: "confirmed",
      amount_field_status: "confirmed",
      cadence_field_status: "confirmed",
      renewal_field_status: "confirmed",
      status_field_status: "confirmed",
      amount_confidence: "high",
      cadence_confidence: "high",
      renewal_confidence: "high",
      provider_confidence: "high",
      status_confidence: "high",
      deferred_until: null,
    },
    claudePro: {
      key: "claudePro",
      id: SEED_SUBSCRIPTION_IDS.claudePro,
      user_id: SEED_USER_ID,
      provider_canonical: "claude-pro",
      provider_display: "Claude Pro",
      plan: "Pro",
      account_hint: null,
      status: "active",
      amount_minor: 1800,
      currency: "GBP",
      cadence: "monthly",
      next_renewal: dateAtOffset(today, 18),
      started_on: dates.startedOn,
      ends_on: null,
      notes: null,
      provider_field_status: "confirmed",
      amount_field_status: "confirmed",
      cadence_field_status: "confirmed",
      renewal_field_status: "confirmed",
      status_field_status: "confirmed",
      amount_confidence: "high",
      cadence_confidence: "high",
      renewal_confidence: "high",
      provider_confidence: "high",
      status_confidence: "high",
      deferred_until: null,
    },
    cursor: {
      key: "cursor",
      id: SEED_SUBSCRIPTION_IDS.cursor,
      user_id: SEED_USER_ID,
      provider_canonical: "cursor",
      provider_display: "Cursor",
      plan: "Pro",
      account_hint: null,
      status: "active",
      amount_minor: 2000,
      currency: "GBP",
      cadence: "monthly",
      next_renewal: dateAtOffset(today, 24),
      started_on: dates.startedOn,
      ends_on: null,
      notes: null,
      provider_field_status: "confirmed",
      amount_field_status: "confirmed",
      cadence_field_status: "confirmed",
      renewal_field_status: "confirmed",
      status_field_status: "confirmed",
      amount_confidence: "high",
      cadence_confidence: "high",
      renewal_confidence: "high",
      provider_confidence: "high",
      status_confidence: "high",
      deferred_until: null,
    },
    github: {
      key: "github",
      id: SEED_SUBSCRIPTION_IDS.github,
      user_id: SEED_USER_ID,
      provider_canonical: "github",
      provider_display: "GitHub",
      plan: "Copilot",
      account_hint: null,
      status: "active",
      amount_minor: 9600,
      currency: "GBP",
      cadence: "yearly",
      next_renewal: dateAtOffset(today, 45),
      started_on: dates.startedOn,
      ends_on: null,
      notes: null,
      provider_field_status: "confirmed",
      amount_field_status: "confirmed",
      cadence_field_status: "confirmed",
      renewal_field_status: "confirmed",
      status_field_status: "confirmed",
      amount_confidence: "high",
      cadence_confidence: "high",
      renewal_confidence: "high",
      provider_confidence: "high",
      status_confidence: "high",
      deferred_until: null,
    },
    adobe: {
      key: "adobe",
      id: SEED_SUBSCRIPTION_IDS.adobe,
      user_id: SEED_USER_ID,
      provider_canonical: "adobe",
      provider_display: "Adobe",
      plan: "Creative Cloud",
      account_hint: null,
      status: "active",
      amount_minor: 5999,
      currency: "GBP",
      cadence: "monthly",
      next_renewal: dateAtOffset(today, 16),
      started_on: dates.startedOn,
      ends_on: null,
      notes: "Amount inferred from recent billing history.",
      provider_field_status: "confirmed",
      amount_field_status: "inferred",
      cadence_field_status: "inferred",
      renewal_field_status: "inferred",
      status_field_status: "confirmed",
      amount_confidence: "medium",
      cadence_confidence: "medium",
      renewal_confidence: "medium",
      provider_confidence: "high",
      status_confidence: "high",
      deferred_until: null,
    },
    notion: {
      key: "notion",
      id: SEED_SUBSCRIPTION_IDS.notion,
      user_id: SEED_USER_ID,
      provider_canonical: "notion",
      provider_display: "Notion",
      plan: "Plus trial",
      account_hint: null,
      status: "trial",
      amount_minor: null,
      currency: "GBP",
      cadence: "monthly",
      next_renewal: dates.trialEndsOn,
      started_on: dateAtOffset(today, -2),
      ends_on: null,
      notes: null,
      provider_field_status: "confirmed",
      amount_field_status: "empty",
      cadence_field_status: "proposed",
      renewal_field_status: "proposed",
      status_field_status: "confirmed",
      amount_confidence: null,
      cadence_confidence: "medium",
      renewal_confidence: "medium",
      provider_confidence: "high",
      status_confidence: "high",
      deferred_until: null,
    },
    onePassword: {
      key: "onePassword",
      id: SEED_SUBSCRIPTION_IDS.onePassword,
      user_id: SEED_USER_ID,
      provider_canonical: "1password",
      provider_display: "1Password",
      plan: "Families",
      account_hint: null,
      status: "cancel_scheduled",
      amount_minor: 3599,
      currency: "GBP",
      cadence: "yearly",
      next_renewal: dates.renewalWithin30,
      started_on: dates.startedOn,
      ends_on: dates.cancelEndsOn,
      notes: "Cancellation takes effect at the end of the paid period.",
      provider_field_status: "confirmed",
      amount_field_status: "confirmed",
      cadence_field_status: "confirmed",
      renewal_field_status: "confirmed",
      status_field_status: "confirmed",
      amount_confidence: "high",
      cadence_confidence: "high",
      renewal_confidence: "high",
      provider_confidence: "high",
      status_confidence: "high",
      deferred_until: null,
    },
    athletic: {
      key: "athletic",
      id: SEED_SUBSCRIPTION_IDS.athletic,
      user_id: SEED_USER_ID,
      provider_canonical: "the-athletic",
      provider_display: "The Athletic",
      plan: "Digital",
      account_hint: null,
      status: "cancelled",
      amount_minor: 799,
      currency: "GBP",
      cadence: "monthly",
      next_renewal: null,
      started_on: dates.startedOn,
      ends_on: dates.cancelledOn,
      notes: "Historical subscription retained for ledger continuity.",
      provider_field_status: "confirmed",
      amount_field_status: "confirmed",
      cadence_field_status: "confirmed",
      renewal_field_status: "confirmed",
      status_field_status: "confirmed",
      amount_confidence: "high",
      cadence_confidence: "high",
      renewal_confidence: "high",
      provider_confidence: "high",
      status_confidence: "high",
      deferred_until: null,
    },
    disneyPlus: {
      key: "disneyPlus",
      id: SEED_SUBSCRIPTION_IDS.disneyPlus,
      user_id: SEED_USER_ID,
      provider_canonical: "disney-plus",
      provider_display: "Disney+",
      plan: null,
      account_hint: null,
      status: "unknown",
      amount_minor: null,
      currency: "GBP",
      cadence: null,
      next_renewal: null,
      started_on: null,
      ends_on: null,
      notes: "Provider identified; terms need attention.",
      provider_field_status: "confirmed",
      amount_field_status: "empty",
      cadence_field_status: "empty",
      renewal_field_status: "empty",
      status_field_status: "proposed",
      amount_confidence: null,
      cadence_confidence: null,
      renewal_confidence: null,
      provider_confidence: "high",
      status_confidence: "medium",
      deferred_until: null,
    },
  } satisfies Record<SubscriptionKey, SeedSubscription>;

  const subscriptions = Object.values(subscriptionRows).map((row) => {
    const { key, ...subscription } = row;
    void key;
    return subscription;
  }) satisfies SubscriptionInsert[];
  const amendments = Object.values(subscriptionRows).map((subscription) => {
    return {
      id: SEED_AMENDMENT_IDS[subscription.key],
      user_id: SEED_USER_ID,
      subscription_id: subscription.id,
      effective_from: subscription.started_on ?? dates.today,
      effective_to: null,
      amount_minor: subscription.amount_minor,
      currency: "GBP",
      cadence: subscription.cadence,
      plan: subscription.plan,
    };
  }) satisfies AmendmentInsert[];

  const events = Object.values(subscriptionRows).map((subscription) => {
    return {
      id: SEED_EVENT_IDS[subscription.key],
      user_id: SEED_USER_ID,
      subscription_id: subscription.id,
      type: "started",
      at: subscription.started_on
        ? new Date(`${subscription.started_on}T00:00:00.000Z`)
        : dates.eventAt,
      confirmed: true,
      rationale: "Seeded development subscription.",
      payload: null,
      capture_id: null,
    };
  }) satisfies EventInsert[];

  const charges = [
    {
      id: chargeIds.netflix,
      user_id: SEED_USER_ID,
      subscription_id: subscriptionRows.netflix.id,
      paid_on: dates.recentChargeOn,
      amount_minor: 1599,
      currency: "GBP",
      covers_from: dates.recentChargeOn,
      covers_to: dates.renewalSoon,
      capture_id: null,
      idempotency_key: "seed-netflix-2026-01",
    },
    {
      id: chargeIds.spotify,
      user_id: SEED_USER_ID,
      subscription_id: subscriptionRows.spotify.id,
      paid_on: dates.olderChargeOn,
      amount_minor: 1199,
      currency: "GBP",
      covers_from: dates.olderChargeOn,
      covers_to: dates.recentChargeOn,
      capture_id: null,
      idempotency_key: "seed-spotify-2025-12",
    },
  ] satisfies ChargeInsert[];
  return { user, subscriptions, amendments, events, charges };
}
